#!/usr/bin/env bash
#The script starts printing lines when it encounters the string "ANSWER SECTION:" 
#and stops printing lines when it encounters the end of the answer section.
#The read command is used to assign the values of the variables sub, rtype, 
#and dest by extracting the values from the line variable.
#the FS variable to define the field separator as a dot (.) and then printing the first field of the input
show_subdom () {
    line=$(dig $1 | awk 'c&&!--c;/ANSWER SECTION:/{c=1}')
    read -r sub rtype dest<<< $(echo "$line" | awk '{print $1, $4, $5}')
    sub=$(echo "$sub" | awk 'BEGIN {FS="."} {print $1} END{}')
    echo The subdomain "$sub" is a "$rtype" record and points to "$dest"
}
show_all () {
    subs=(www.$1 lb-01.$1 web-01.$1 web-02.$1)
    for sub in ${subs[@]}
    do
    show_subdom $sub
    done
}
if [ ! -z $2 ]
then
show_subdom $2.$1
else
show_all $1
fi
