#!/usr/bin/env bash
#this scripts used to transfer files from client to server

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file="$1"
server="$2"
username="$3"
key="$4"

scp -o StrictHostKeyChecking=no -i "$key" "$file" "$username@$server:~/"
