#!/usr/bin/env bash
#why you no love me
echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command; /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo Y U no love me?!" SIGINT
var=0
while [[ $var -lt 1 ]];
do
  echo "To infinity and beyond"
  sleep 2
done
