#!/usr/bin/env bash
#using while statements to print strings
VALUE=1
while [ $VALUE -le 10 ];
 do 
   echo "Best School"
   if [[ $VALUE -eq 9 ]]
   then
	   echo "Hi"
   fi
   ((VALUE=VALUE+1))
done
