#!/usr/bin/env bash
# Run Nginx as Nginx
sudo pkill apache2
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chown 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
